### ISSUE TITLE
Small typo on the readme file

### ISSUE THREAD

**Issue by AliNemat** [xinyu-dev/igblast#2]
Thanks for great description of setting up database for IgBlast which is very helpful.
I think there is a small typo in this command at the very end.

> bin/edit_imgt_file.pl database/Homo_sapiens/IG_prot/IGKV > database/Homo_sapiens_clean/IG_prot/IGHV_KV_clean

I think it should be

> bin/edit_imgt_file.pl database/Homo_sapiens/IG_prot/IGKV > database/Homo_sapiens_clean/IG_prot/IGKV_clean

**Comment by xinyu-dev** [comment]
Thank you for pointing it out! It has been corrected in both readme and juptyer notebook files
